
# Automatically generated by: python manage.py create_local_config

SECRET_KEY ='bd19d213dcdb6c444759fe9404dd3003d6d736e3f999a914'

ACCOUNT_VERIFICATION_SECRET ='b9688f02e3e32db123dd209bdc076df3297bb6ed28ae2fa3'

DEBUG = False

CLASSIC_LOGIN_URL = 'http://adsabs.harvard.edu/cgi-bin/maint/manage_account/credentials'

SITE_SECURE_URL = 'http://0.0.0.0:5000'